### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [ConvertAPI/convertapi-node#1]
When i say `npm install convertapi -S` it is not installing anything. The directory just has two files. One is index.js and the other is package.json. The index.js has only three lines.
````
module.exports = {
    salute: global.console.log("Hello, world")
};

````
Nothing else. So the installation itself not working. How can you expect to pay for `convertapi` for such useless thing.

**Comment by laurynas-baltsoft** [comment]
Hi, we have just released npm package with organisation scope, because `convertapi` name is currently used by this empty project you mentioned.

Please use organisation scoped package:
```
npm install @convertapi/convertapi --save
```

Adjusted readme.  Sorry about this inconvenience.

**Comment by rajeshwarpatlolla** [comment]
Thanks for the update.
