### ISSUE TITLE
saveFiles method doesnt work as it said in documentation

### ISSUE THREAD

**Issue by zlydenko** [ConvertAPI/convertapi-node#11]
Method saveFiles require path for saving range of files, but it take path as filename and save only last one. :clap: :clap:

**Comment by laurynas-baltsoft** [comment]
Tested, and actually it works fine for me - multiple files are stored.
Example:
https://github.com/ConvertAPI/convertapi-node/blob/master/examples/convert_word_to_pdf_and_png.js#L31

Did you pass existing directory path to the `saveFiles`?
