### ISSUE TITLE
IInvalid structure of a zip file

### ISSUE THREAD

**Issue by minedun6** [ConvertAPI/convertapi-node#14]
Is there any possible way to keep the extracted files of a zip file with their structure ?

Ex:
```json
{ "FileName": "Summary.png",
  "FileSize": 11017,
  "FileId": "2bfa1b8f2649d9b54ebd825c20a17721",
  "Url": "https://v2.convertapi.com/d/2bfa1b8f2649d9b54ebd825c20a17721/Summary.png" }
```

This file should be under another folder but it is not.

Can you guys help me ?

**Comment by tomasr78** [comment]
THis is not possible, our API extract files from ZIP and not path/file structure.
