### ISSUE TITLE
Typescript type declarations

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-node#15]
Create Typescript type declarations

**Comment by tomasr78** [comment]
Please explain more detailed the usage case?

**Comment by JonasJasas** [comment]
Write typescript typings file used for validation and autocompletion.
https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html

**Comment by Kenny407** [comment]
Hello, is there any update regarding this @laurynas-baltsoft @tomasr78 ? It'd be nice to have some types for the library. Any way that we can help ?

**Comment by laurynas-baltsoft** [comment]
Added declarations and released `v1.7.0`

**Comment by Kenny407** [comment]
@laurynas-baltsoft thanks for the update! I will give it a try 🎉
