### ISSUE TITLE
Not routing through system proxy

### ISSUE THREAD

**Issue by mattcee233** [ConvertAPI/convertapi-node#17]
I'm trying to use ConvertAPI on Node v12.4.0 behind a corporate proxy but the node library doesn't appear to be following the system default or nodes specific proxy settings. 

Is there a way to set a proxy specifically for ConvertAPI library or does this need adding?

**Comment by laurynas-baltsoft** [comment]
I have added proxy support in the latest `1.3.0` version:

```javascript
var convertapi = require('convertapi')('your-api-secret', {
  proxy: {
    host: '127.0.0.1',
    port: 9000,
    auth: {
      username: 'testuser',
      password: 'secret'
    }
  }
});
```
