### ISSUE TITLE
How to get the file object

### ISSUE THREAD

**Issue by Bennoo** [ConvertAPI/convertapi-node#19]
Hello there, 
I'm not able to find how to get the converted file without saving it locally (I'm working with readOnly environment).
I would like to get the file object and manipulate it without having to save it locally with File.save('path').

Is it possible?

Many thanks,

**Comment by laurynas-baltsoft** [comment]
Hi @Bennoo, you can get file url like this:
`result.file.url`

You can fetch file data from the url.

https://github.com/ConvertAPI/convertapi-node/blob/master/src/result_file.js
