### ISSUE TITLE
Change HTTP request Agent header format

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-node#2]
Change HTTP request Agent header format form old format

convertapi-nodejs-version

to

ConvertAPI-NodeJS/version or ConvertAPI-Node/version

Choose which better from two above.

Such format is more native to HTTP agent specification http://www.bizcoder.com/the-much-maligned-user-agent-header

**Comment by laurynas-baltsoft** [comment]
Done, published version v1.0.1
