### ISSUE TITLE
I tried to compress api

### ISSUE THREAD

**Issue by otograde** [ConvertAPI/convertapi-node#21]
It will not workout, it throws promise error. May i know how can i use compress api in node js.
Error : 
**Unhandled Rejection at: Promise Promise {
  <rejected> { Error: read ECONNRESET**

Here is my code : 
var convertapi = require('convertapi')('<< Secret Key >>'); //not api secret key

convertapi.convert('compress', {
   File: './public/report/report-1.pdf'
}, 'pdf').then(function(result) {
    result.saveFiles('./public/report/report-1.pdf');
});

**Comment by laurynas-baltsoft** [comment]
Hi, looks like you are getting network error - maybe it was temporary. Can you try again? Would you still get the same error?
