### ISSUE TITLE
Compress api get buffer as input

### ISSUE THREAD

**Issue by nisharg007** [ConvertAPI/convertapi-node#22]
Can I get buffer as input in compress API?

https://www.convertapi.com/pdf-to-compress

Please Explain what is File ID in your site? 

Thanks!!

**Comment by laurynas-baltsoft** [comment]
You can send stream to the API first and then pass it to the converted. Here is the example:
https://github.com/ConvertAPI/convertapi-node/blob/master/examples/convert_stream.js

FileID is unique ID which is assigned to the uploaded file and it can be passed to the converter. But you don't need to worry about it as node client handles it internally (as seen in the example above).

**Comment by nisharg007** [comment]
This is not valid solution for that, I need file for createReadStream() because it can't read buffer

**Comment by laurynas-baltsoft** [comment]
@nisharg007 here you can find an example with buffer:
https://github.com/ConvertAPI/convertapi-node/blob/master/examples/convert_base64_content.js

Hope it helps.

**Comment by nisharg007** [comment]
Thanks, that example works fine 😁
