### ISSUE TITLE
How to get output in base64 buffer

### ISSUE THREAD

**Issue by nisharg007** [ConvertAPI/convertapi-node#23]
I used your API and I found out that in `convert-api` node module, I don't get base64 buffer from your response but I get base64 buffer response from your URL request ( https://v2.convertapi.com/convert/pdf/to/compress?Secret=** )

In node package, I get compress image in form of your storage URL, but I want base64 buffer.

WHY This type of difference output in URL request and module request?

Can I get formData/base64 Buffer from node package?

Thanks

**Comment by rostyslavkhaniukov** [comment]
It is the bug in order arguments: https://github.com/ConvertAPI/convertapi-node/blob/cee6ae9d673b9b2991b514a5cfce19a06ec06355/src/task.js#L28

**Comment by NishargShah** [comment]
> It is the bug in order arguments:
> 
> https://github.com/ConvertAPI/convertapi-node/blob/cee6ae9d673b9b2991b514a5cfce19a06ec06355/src/task.js#L28

so how can I solve it? 

It is possible to get a buffer in output?

**Comment by nisharg007** [comment]
> 
> 
> It is the bug in order arguments:
> 
> https://github.com/ConvertAPI/convertapi-node/blob/cee6ae9d673b9b2991b514a5cfce19a06ec06355/src/task.js#L28

so how can I solve it?

It is possible to get a buffer in output?

**Comment by laurynas-baltsoft** [comment]
Converted file url is accessible via `result.files[0].url`. You can read it as a binary stream. 
It is more effective than getting encoded file body in the JSON response.

Here is an example how you can read converted file to a string:
https://github.com/ConvertAPI/convertapi-node/blob/master/examples/get_result_file_stream.js

**Comment by nisharg007** [comment]
Thanks, that works fine 😀
