### ISSUE TITLE
Certain PDF yields 415 if used with node API

### ISSUE THREAD

**Issue by Burgov** [ConvertAPI/convertapi-node#28]
So I wan't able to reproduce this issue using the form on your website or with Postman. Using those tools, the conversion runs fine. But I've created a repo that perfectly demonstrates the issue when using the node API: https://github.com/MSP-Navigator/convertapi-issue

As you can see there's two PDFs in there. One works, the other yields a 415 error. Any idea what could be the cause?

**Comment by WebBlacksmith** [comment]
The issue is with the character "(" or ")". It fails when those characters are in the name file. 

I have the same issue.

**Comment by tomasr78** [comment]
We will fix the issue this or next week.

**Comment by tomasr78** [comment]
@laurynas-baltsoft The **HTTP 415 Unsupported Media Type** means that an uploaded file is not supported by ConvertAPI though the participants tried to upload supported files like **.PDF**. It could be that () symbols in a file break file upload in NodeJS.

**Comment by Burgov** [comment]
@WebBlacksmith thanks for the hint. I've stripped special characters from the filename, and now it goes through fine 👍

**Comment by tomasr78** [comment]
@laurynas-baltsoft Please make the test case for https://github.com/ConvertAPI/convertapi-php as well, if I remember correctly some developers complained about a similar problem.

**Comment by laurynas-baltsoft** [comment]
[Fixed](https://github.com/ConvertAPI/convertapi-node/commit/30adc3f87e45def59e59064ef68d63fadbb0e863) issue and released 1.6.1 client version. 

@tomasr78 I have checked PHP client - it works fine with the () symbols in the filename.
