### ISSUE TITLE
 Server-Side Request Forgery vuln

### ISSUE THREAD

**Issue by DecisionFocus** [ConvertAPI/convertapi-node#30]
High          │ Server-Side Request Forgery                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.21.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ convertapi                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ convertapi > axios                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1594

**Comment by laurynas-baltsoft** [comment]
Updated dependency & released 1.8.0 version.
