### ISSUE TITLE
Review PR for typings in DefinitelyTyped

### ISSUE THREAD

**Issue by Kenny407** [ConvertAPI/convertapi-node#33]
The [DefiniteTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository is a perfect place to maintain the types of the library. 

I have made a PR to add them here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50684 @laurynas-baltsoft  Could you please review it ? Of course I gave you credits for the update 👏🏼  thanks again.

We will be able to do: `npm install --save convertapi` and `npm install --save-dev @types/convertapi` after it gets merged. 

Feel free to close this issue when you have reviewed it.

**Comment by peterblazejewicz** [comment]
I think 1.9.0 was not yet published properly on NPM. `index.d.ts` should be picked by TypeScript `tsc` (VSCode, etc) once it's published to NPM and intals with package. It's following the convention:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
In the other words, IMO there is no need to separately publish @types/***
Thx!

**Comment by Kenny407** [comment]
Thanks for the quick response @peterblazejewicz I agree with you. 

I'm wondering what happened with the `1.9.0` I just did a fresh install of `convertapi@1.9.0` and the types were not picked up although I see them in the source of the project. I will check the config.

**Comment by laurynas-baltsoft** [comment]
Thanks for the PR, we already [fixed](https://github.com/ConvertAPI/convertapi-node/commit/88bb0efbb0d6317d1ce6350c4368b455e86f9003) this issue and released 1.9.1 version.
