### ISSUE TITLE
StoreFile is set to true, should be false & normalizeParams should be updated

### ISSUE THREAD

**Issue by eyingling02** [ConvertAPI/convertapi-node#38]
1) According to the documentation, this StoreFile param should be set to False:
https://github.com/ConvertAPI/convertapi-node/blob/af052a3a3b98de637abf937df2e341a8e7a80931/src/task.js#L11
![Screen Shot 2021-02-25 at 1 03 54 PM](https://user-images.githubusercontent.com/17955817/109219977-2f155580-776d-11eb-9f92-897b880ff8f2.png)

2)The ordering of the args passed into Object.assign() should be switched to `Object.assign({}, this.defaultParams, params)`
because the way this code is currently written, `this.defaultParams` will always be stored over the params that a user passes in
https://github.com/ConvertAPI/convertapi-node/blob/af052a3a3b98de637abf937df2e341a8e7a80931/src/task.js#L33

**Comment by tomasr78** [comment]
The StoreFile property is set to True by default in all libraries. If you want you can branch the library source and set StoreFile=false

**Comment by eyingling02** [comment]
Then this needs to be updated:
![Screen Shot 2021-02-25 at 1 43 12 PM](https://user-images.githubusercontent.com/17955817/109223445-700e6980-776f-11eb-947d-18e230c28677.png)

**Comment by eyingling02** [comment]
Also, after speaking to your CTO, he said that the default is set to False

**Comment by tomasr78** [comment]
There are two different things, the StoreFile=false for the API and the library uses StoreFile=true because it allows using workflow.
You can just ignore the library and use pure NodeJS code written and adjusted by yourself.

**Comment by eyingling02** [comment]
Right now, the way Object.assign is written under normalizeParams always assigns the defaultParams over the passed in params, so right now when we try to pass `StoreFile: false` to the api, the library always overrides it

**Comment by tvillafane** [comment]
This is kind of not cool, honestly.
