### ISSUE TITLE
Why I got TypeError: _fs2.default.createReadStream is not a function

### ISSUE THREAD

**Issue by woohelps** [ConvertAPI/convertapi-node#41]
When I try to use convertapi convert word to png, I got errors:

`index.js:1 TypeError: _fs2.default.createReadStream is not a function`

`import ConvertAPI from 'convertapi'; 

 const convertapi = new ConvertAPI(mysecret);
        console.log(dataTransfer.files[0]);
        convertapi.convert('png', { File: dataTransfer.files[0] })
            .then(function (result) {
                console.log(result);
            })
            .catch(function (e) {
                console.error(e.toString());
            });`

Here is the dataTransfer.files[0]:
![image](https://user-images.githubusercontent.com/74527670/130695109-21b26e6b-a152-402e-8dea-6694c8999569.png)

**Comment by laurynas-baltsoft** [comment]
ConvertAPI Node.js library is intended to work only with backend applications, it won't work from the browser.
