### ISSUE TITLE
Do not pass any TimeOut property to ConvertAPI and set HTTP Client timeout to 1800 seconds

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-node#42]
Do not pass any default TimeOut property to ConvertAPI and set HTTP Client timeout to 1800 seconds. The idea is to use the default converter timeout of ConvertAPI if no timeout is set and to prevent HTTP Client request deadlock set default HTTPClient timeout to 1800 seconds.

If, however, timeout is set we handle it as before, pass a timeout to ConvertAPI and set HTTPClient Timeout to: ConvertAPITimeOut+conversion_timeout_delta

conversion_timeout_delta = 10

**Comment by tomasr78** [comment]
Related https://github.com/ConvertAPI/convertapi-dotnet/issues/24

**Comment by laurynas-baltsoft** [comment]
Conversion timeout is not set by default. If it is enabled, `conversionTimeoutDelta` is used for http client.
