### ISSUE TITLE
compare API is returning -  Code: 5009, Message: 'File id is not valid.' 

### ISSUE THREAD

**Issue by vaibhav-srivastava-sf** [ConvertAPI/convertapi-node#55]
compare API is returning -  Code: 5009, Message: 'File id is not valid.'  with NodeJS

`let http = require('http');
let formidable = require('formidable');
let fs = require('fs');

http.createServer(function (req, res) {

  //Create an instance of the form object
  let form = new formidable.IncomingForm();

  //Process the file upload in Node
  form.parse(req, function (error, fields, file) {
    let filepath = file.fileupload1.filepath;
    let newpath1 = '/path_to_folder/compare-docs/';
    newpath1 += file.fileupload1.originalFilename;

    //Copy the uploaded file to a custom folder
    fs.rename(filepath, newpath1, function () {
        /* will handle later */ 
    });

    filepath = file.fileupload2.filepath;
    let newpath2 = '/path_to_folder/compare-docs/';
    newpath2 += file.fileupload2.originalFilename;

    //Copy the uploaded file to a custom folder
    fs.rename(filepath, newpath2, function () {
        /* will handle later */ 
       // res.write('NodeJS File Upload Success!');
        //res.end();
    });
```
try{
  let convertapi = require('convertapi')('MY API KEY');
    console.log('newpath1: ',newpath1);
    console.log('newpath2: ',newpath2);
  convertapi.convert('compare', {
      File: newpath1,
      CompareFile: newpath2
  }, 'docx').then(function(result) {
      result.saveFiles('/path_to_folder/compare-docs/');
  });
}
catch(e){
  console.log(e);
}
  });
}).listen(800);`
```

**Comment by tomasr78** [comment]
Duplicate https://github.com/ConvertAPI/convertapi-node/issues/60
