### ISSUE TITLE
Update axios version to 1.6.0

### ISSUE THREAD

**Issue by y-meguro** [ConvertAPI/convertapi-node#73]
Hi, I would like to inform you about the CSRF vulnerability issue in axios.
I would appreciate it if you could update the axios.

### Expected Behavior
Axios version used is 1.6.0, to resolve known CSRF vulnerability.

### Actual Behavior
Current version used is 0.21.1, which is vulnerable to CSRF: https://security.snyk.io/package/npm/axios/0.21.1.

Thank you in advance.

**Comment by y-meguro** [comment]
Thanks for resolving my issue.
Could you share the expected release date for the next version?

**Comment by laurynas-baltsoft** [comment]
Released version v1.14.0
https://github.com/ConvertAPI/convertapi-node/releases/tag/v1.14.0
