### ISSUE TITLE
Is there a way to pass a file buffer or stream instead of a path?

### ISSUE THREAD

**Issue by jpintoic** [ConvertAPI/convertapi-node#79]
Instead of:
```javascript
convertapi.convert('pdf', { File: '/path/to/my_file.docx' })
```
Coult it be possible to do:
```javascript
convertapi.convert('pdf', { File: myBuffer })
```

Same thing with the `result.file.save(path)` function. Instead of giving it a path it would be great if we could save the file directly to `Buffer` or `Stream` without having to write the file to disk.

Otherwise, I have to download the file from storage and then write it to disk just so I can have a file path to pass into the convert function.

I have also tried using a download presigned URL from AWS S3 in place of the path, but that also didn't work and threw an error.

**Comment by tomasr78** [comment]
You can pass the file URL directly to our converter, try it here https://www.convertapi.com/docx-to-pdf
Change from file to URL and enter remote url to  AWS S3, the file should be accessible and not protected.

<img width="1050" alt="image" src="https://github.com/ConvertAPI/convertapi-node/assets/2582291/710c3442-d847-4801-823c-65b438107c04">

NodeJS code

```js
var convertapi = require('convertapi')('secret');
convertapi.convert('pdf', {
    File: 'https://url-to/S3'
}, 'docx').then(function(result) {
    result.saveFiles('/path/to/dir');
});

```
