### ISSUE TITLE
Add Token authentication

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-node#83]
Add `Token `and `Self Generated Token` authentication. The endpoint should receive two parameters `Token and ApiKey`.

`https://v2.convertapi.com/convert/docx/to/pdf?Token={Token}&ApiKey={ApiKey}`

The Token authorization with different tokens can be used in the application and it should be an easy way to change Token parameters on runtime. That's the main difference between Token and Secret authentication. 

Related https://github.com/ConvertAPI/convertapi-dotnet/issues/30

**Comment by tomasr78** [comment]
Finally, we have four authentication methods. Below is the description from the C# code.

1. Authentication using static Secret variable

``` csharp
public static string Secret;
```

2. Authentication using static Token variable

``` csharp
public static string Token;
public static int ApiKey;
```

3. Authentication using Secret constructor

``` csharp
public ConvertApi(string secret)
```

4. Authentication using Token constructor

``` csharp
public ConvertApi(string token, int apiKey)
```

**Comment by tomasr78** [comment]
Create a token authentication demo and add a description in the readme file.

**Comment by tomasr78** [comment]
Not relevant anymore.

**Comment by Yukaii** [comment]
Hi @tomasr78, I want to check the status of this issue. What's the meaning of "not relevant"? Is the token-based authentication being addressed, or are you not going to implement this anymore? Thank you 🙏🏼

**Comment by tomasr78** [comment]
Not relevant anymore due to the change in authentication method. More information available at https://github.com/ConvertAPI/convertapi-node/issues/85. When this change is implemented, tokens will be supported out of the box.

**Comment by Yukaii** [comment]
Got it! Thank you
